theme = "blowfish"
baseURL = "https://auto.insidemordecai.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

buildDrafts = false
buildFuture = false

enableEmoji = true

# googleAnalytics = "G-EKK1X50BK7"

[permalinks]
  posts = '/:slug/'

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
