languageCode = "en"
languageName = "English"
weight = 1
title = "Drive Talks"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  description = "Car and Motorsport Blog | Drive Talks (by Mordecai Kipng'etich)"
  copyright = "No Rights Reserved"


[author]
  name = "Mordecai Kipng'etich"
  image = "img/profile.png"
  # headline = ""
  bio = "Motorsport Enthusiast and Software Developer"
  links = [
    { email = "mailto:contact@insidemordecai.com" },
    { twitter = "https://twitter.com/insidemordecai" },
	{ github = "https://github.com/insidemordecai" },
    { linkedin = "https://linkedin.com/in/insidemordecai" },
  ]
