languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Drive Talks"
# logo = "img/logo.png"
description = "Car and Motorsport Blog | Drive Talks from Mordecai Kipng'etich"
copyright = "No Rights Reserved"

dateFormat = "2 January 2006"

[author]
  name = "Mordecai Kipng'etich"
  image = "img/profile.png"
  # headline = ""
  bio = "Motorsport Enthusiast and Software Developer"
  links = [
    { email = "mailto:contact@insidemordecai.com" },
    { twitter = "https://twitter.com/insidemordecai" },
	{ github = "https://github.com/insidemordecai" },
    { linkedin = "https://linkedin.com/in/insidemordecai" },
  ]
