# -- Theme Options --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "marvel"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
replyByEmail = true
disableImageOptimization = true
defaultBackgroundImage = "img/background.jpg"

smartTOC = true
smartTOCHideUnfocusedChildren = false

# mainSections = ["section1", "section2"]
# robots = ""

[header]
  layout = "fixed" # valid options: basic, fixed

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false 
  showScrollToTop = true

[homepage]
  layout = "page" 
  homepageImage = "img/background.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "background" 
  layoutBackgroundBlur = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true 
  showAuthorsBadges = false 
  showWordCount = false
  showSummary = true
  sharingLinks = false # [ "linkedin", "twitter", "whatsapp", "reddit", "facebook", "email"]

[list]
  showHero = true
  heroStyle = "background" 
  layoutBackgroundBlur = true 
  layoutBackgroundHeaderSpace = true 
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showSummary = true
  showTableOfContents = false
  showCards = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true

[firebase]
  # apiKey = "AIzaSyDxG2OJ7Mx_a_r7-CjaxQYngS3l3LdCDyE"
  # authDomain = "auto-insidemordecai.firebaseapp.com"
  # projectId = "auto-insidemordecai"
  # storageBucket = "auto-insidemordecai.appspot.com"
  # messagingSenderId = "494489497764"
  # appId = "1:494489497764:web:cf0f549bd165a0d891b631"
  # measurementId = "G-EKK1X50BK7"

[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
